export const GET_POSTS_PENDING = "GET_POSTS_PENDING";
export const GET_POSTS_FULFILLED = "GET_POSTS_FULFILLED";
export const GET_POSTS_REJECTED = "GET_POSTS_REJECTED";
export const DISMISS_POST = "DISMISS_POST";
